// Scene timing generated by scripts/generate_voiceover.py from the narration audio.
import data from "./data/timeline.json";

export type SceneId = "france" | "chaos" | "reveal" | "toulouse" | "rates" | "outro";

export type SceneTiming = {
  id: SceneId;
  from: number;
  durationInFrames: number;
  audio: { src: string; from: number; durationMs: number; speechEndMs: number };
  chunks: { text: string; startMs: number; endMs: number }[];
  marks: Record<string, number>;
};

export type CaptionEntry = {
  sceneId: SceneId;
  text: string;
  startMs: number;
  endMs: number;
};

export const FPS: number = data.fps;
export const TOTAL_FRAMES: number = data.durationInFrames;
export const SCENES = data.scenes as unknown as SceneTiming[];
export const CAPTIONS = data.captions as CaptionEntry[];

// Frames by which each scene overlaps the next one for a cross-fade.
export const SCENE_OVERLAP = 12;

export const scene = (id: SceneId): SceneTiming => {
  const found = SCENES.find((s) => s.id === id);
  if (!found) throw new Error(`Unknown scene ${id}`);
  return found;
};

export const msToFrames = (ms: number) => Math.round((ms / 1000) * FPS);

/** Frame (relative to the scene start) at which an emphasized word is spoken. */
export const markFrame = (id: SceneId, word: string, fallback = 0) => {
  const ms = scene(id).marks[word];
  return ms === undefined ? fallback : msToFrames(ms);
};

/** Frame (relative to the scene start) at which a narration chunk begins. */
export const chunkFrame = (id: SceneId, index: number) =>
  msToFrames(scene(id).chunks[index]?.startMs ?? 0);
